[package]
name = "dispatcher-crate"
version.workspace = true
edition.workspace = true

[lib]
name = "dispatcher"
crate-type = ["cdylib", "rlib"]

[dependencies]
neural-core = { path = "../neural_core" }
llama = { path = "../llama" }
onnx = { path = "../onnx" }
system-booster = { path = "../../inference-engine/engines/system-booster" }
cluaiz-shared = { path = "../../inference-engine/engines/cluaiz-shared" }
anyhow = "1.0"
async-trait = "0.1"
tracing = "0.1"
tokio = { version = "1.0", features = ["full"] }
