[workspace]
members = [
    "cluaiz-cure/api",
    "cluaiz-cure/engines",
    "cluaiz-cure/engines/candle",
    "cluaiz-cure/engines/archer-shared",
    "cluaiz-cure/engines/llama",
    "cluaiz-cure/engines/bitnet",
    "cluaiz-cure/engines/system-booster",
    "cluaiz-cure/shared",
    "Apps/cli",
    "brain/storage",
    "driver-manager"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Aryan <creator@cluaiz.os>"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
