[workspace]
members = [
    "inference-engine/api",
    "inference-engine/engines",
    "inference-engine/engines/cluaiz-shared",
    "inference-engine/engines/system-booster",
    "cmd",
    "test/dummy_plugin"
, "inference-cel"]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Cluaiz Technologies"]

[profile.dev]
debug = false
split-debuginfo = "off"
