 [workspace]
members = [
    "cluaiz-engine/api",
    "cluaiz-engine/engines",
    "cluaiz-engine/engines/cluaiz-shared",
    "cluaiz-engine/engines/system-booster",
    "Apps/cli", "interface-engines/onnx",
]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha"
edition = "2021"
authors = ["Aryan (Founder)"]
